debug: true
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/blog

jmore:
  security:
    type: custom
    exclude-paths: /configuration/initialization

mybatis:
  mapper-locations: classpath:mapper/*.xml